# Generated by Django 3.2.4 on 2021-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='ethnicity',
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(choices=[(1, 'Under 18'), (2, '18-24 years old'), (3, '25-34 years old'), (4, '35-44 years old'), (5, '45-54 years old'), (6, '55 years old or older')], default=1),
        ),
    ]
