# Generated by Django 3.2.4 on 2021-09-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0002_auto_20210930_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonassignment',
            name='label_similarity',
        ),
        migrations.RemoveField(
            model_name='comparisonassignment',
            name='raw_similarity',
        ),
        migrations.AddField(
            model_name='comparison',
            name='common',
            field=models.BooleanField(default=False),
        ),
    ]
