# Generated by Django 3.2.4 on 2021-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0003_auto_20210930_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
