# Generated by Django 3.2.4 on 2021-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0004_comparison_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonassignment',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comparisonassignment',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
