# Generated by Django 3.2.4 on 2021-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0005_auto_20211007_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonassignment',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
