# Generated by Django 3.2.4 on 2021-11-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0006_comparisonassignment_reverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='education',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='language',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='race',
        ),
    ]
