# Generated by Django 3.2.4 on 2021-11-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0007_auto_20211111_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ip',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
