# Generated by Django 3.2.4 on 2021-11-13 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0008_participant_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
                ('ip', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_question_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
