# Generated by Django 3.2.4 on 2021-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0010_textquestionresponse_completion_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comparisonassignment',
            index=models.Index(fields=['assigned_participant', 'comparison'], name='aesthetics__assigne_52a231_idx'),
        ),
    ]
