# Generated by Django 3.2.4 on 2021-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aesthetics_labeling', '0011_comparisonassignment_aesthetics__assigne_52a231_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestionresponse',
            name='question_4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
